
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: project_2_development




test:
  <<: *default
  database: project_2_test


production:
  <<: *default
  database: project_2_production
  username: project_2
  password: <%= ENV['PROJECT_2_DATABASE_PASSWORD'] %>
